title       = "bsky"
baseURL     = "https://bluesky-cli.tamnd.com/"
description = "A command line for Bluesky."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/bluesky-cli"
